package com.open.spring.mvc.generic;

public enum EventType {
    TITANIC_PREDICTION,
    ALGORITHM_EXECUTION,
    USER_ACTION,
    GRADE_PREDICTION,
    FACTORIAL_LOG,
    FIBONACCI_LOG,
    ELEMENTARY_LEADERBOARD,
    SCORE_COUNTER
}
