package com.open.spring.mvc.quiz;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.time.Instant;

/**
 * Represents a user's quiz score.
 * This entity is stored in the 'quiz_scores' table.
 */
@Entity
@Table(name = "quiz_scores")
@Data // Lombok: generates getters, setters, toString, equals, and hashCode
@NoArgsConstructor // Lombok: generates a no-argument constructor
@AllArgsConstructor // Lombok: generates a constructor with all fields
public class QuizScore {

    /**
     * Primary key for the quiz score entry.
     * Auto-generated by the database.
     */
    @Id
    @GeneratedValue(strategy = GenerationType.AUTO)
    private Long id;

    /**
     * The username of the quiz participant.
     * Cannot be null.
     */
    @Column(nullable = false)
    private String username;

    /**
     * The score the user achieved on the quiz.
     * Cannot be null.
     */
    @Column(nullable = false)
    private int score;

    /**
     * Timestamp indicating when the quiz score was recorded.
     * Automatically set to the current time at object creation.
     */
    @Column(nullable = false)
    private Instant createdAt = Instant.now();
}